### ISSUE TITLE
ID invalid 

### ISSUE THREAD

**Issue by stablerat** [n1ckoates/quoter#345]
Whenever i try to insert a message ID into the /inspire command, it tells me it’s an invalid integer. i’ve tried multiple different messages and it still doesn’t work no matter what i do. if i cut off some numbers, it’ll send without telling me it’s invalid but it says the ID can’t be found for obvious reasons 
![533671E0-2865-43B1-869D-C95C2A98E3D9](https://github.com/n1ckoates/quoter/assets/141203686/311c0311-a5b4-45be-a56a-1735ec47f8dc)

**Comment by n1ckoates** [comment]
`id` should be an ID of a quote *within* Quoter, not a Discord message ID. You can add a Discord message to Quoter by long pressing/right clicking on the message, then going to Apps > Quote This. Sorry for the confusion!
